layout_spectrum: 0.8595261711161584
typography_spectrum: 0.03325912123546004
color:
  brandStrength: 0.714160346891731
  lightness: 0.26173499575816095
  saturation: 0.260655959835276
  rhythmicContrast: 0.6029604687355459
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: continuous symbols
navigation:
  - name: News
    url: www.bbc.com
    type: external
  - name: News around the world
    url: 'http:/www.bbc.com'
    type: external
